"physics parameter":

  "fluid evolution":
    
    tau0: 0.4        # in fm/c, initial time
    tmax: 30.0       # in fm/c, final evolution time
    norm: 100
    eta_over_s: 0.2
    zeta_over_s: 0.05
    DsT: 0.2
    Tfo: 0.156 # in GeV

  "charm parameter":

    dσ_QQdy: 0.4087 # in mb
    σ_in: 70.0 # in mb

  "initial conditions":
    
    det: :ALICE
    s_NN: 5020 # MeV
    n1: Lead()
    n2: Lead()
    w: 0.5
    k: 1.
    p: 0.
    b: "minBias" #options: tuple (bmin, bmax) or "minBias"
  
  "additional parameters": # please don't change if you don't know what you're doing
    
    tau_eta_par: 0.2
    tau_zeta_par: 15.0
    hq_mass: 1.5 # GeV

"run parameter":
  
  Nev: 1
  checkpoint_interval: 1
  checkpoint_file: "event_by_event_results_debug_full.h5"
  gridpoints: 100
  xmax: 20.0 # fm
  wavenum: [2,3]

"slurm":
  
  max_time: 30
  partition: debug
  work_directory: ./
  cpus_per_job: 20               #Virgo: [cpus_per_job] * [max_concurrent_jobs] < 200
  memory: 12G
  number_of_jobs: 1
  max_concurrent_jobs: 20 
  container_image: /lustre/alice/users/fcapell/julia_apptainer.sif  # Apptainer/Singularity image to run Julia in


